
PROMPT ===========================================
PROMPT Create table XREF_IN_SUB_QUEUE_FI
PROMPT ===========================================


  CREATE TABLE "XREF_IN_SUB_QUEUE_FI" 
   (	"PDM_TABLE_NAME" VARCHAR2(30), 
	"PDM_ID" NUMBER, 
	"PARENT_PDM_ID" NUMBER, 
	"EVENT_TYPE" VARCHAR2(10), 
	"CREATE_DATE" DATE, 
	"PACK_ID" NUMBER, 
	"GROUP_PACK" NUMBER
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) 
  TABLESPACE "&&TABLES_TABLESPACE" 
  PARTITION BY RANGE ("GROUP_PACK") INTERVAL (1) 
  SUBPARTITION BY LIST ("PDM_TABLE_NAME") 
  SUBPARTITION TEMPLATE ( 
    SUBPARTITION "P_BOND_ALT_IDTFCN" VALUES ( 'BOND_ALT_IDTFCN' ), 
    SUBPARTITION "P_BOND_MBS_ALT_IDTFCN" VALUES ( 'BOND_MBS_ALT_IDTFCN' ) ) 
 (PARTITION "P1"  VALUES LESS THAN (1) 
PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255
  STORAGE(INITIAL 65536
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "&&TABLES_TABLESPACE" 
 NOCOMPRESS  LOGGING) ;
PROMPT ===========================================
PROMPT Create indexes on XREF_IN_SUB_QUEUE_FI
PROMPT ===========================================


  CREATE UNIQUE INDEX "UK_XREF_IN_SUB_QUEUE_FI_01" ON "XREF_IN_SUB_QUEUE_FI" ("PDM_TABLE_NAME", "PDM_ID", "PARENT_PDM_ID", "PACK_ID", "GROUP_PACK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "&&INDEX_TABLESPACE"  LOCAL
 (PARTITION "P1" 
PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "&&INDEX_TABLESPACE"  NOLOGGING 
 ( SUBPARTITION "P_BOND_ALT_IDTFCN" 
  TABLESPACE "&&INDEX_TABLESPACE" , 
  SUBPARTITION "P_BOND_MBS_ALT_IDTFCN" 
  TABLESPACE "&&INDEX_TABLESPACE" ) ) ;
PROMPT ===========================================
PROMPT Add constraints on XREF_IN_SUB_QUEUE_FI
PROMPT ===========================================


  ALTER TABLE "XREF_IN_SUB_QUEUE_FI" MODIFY ("PDM_TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XREF_IN_SUB_QUEUE_FI" MODIFY ("PDM_ID" NOT NULL ENABLE);
  ALTER TABLE "XREF_IN_SUB_QUEUE_FI" MODIFY ("PARENT_PDM_ID" NOT NULL ENABLE);
  ALTER TABLE "XREF_IN_SUB_QUEUE_FI" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XREF_IN_SUB_QUEUE_FI" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XREF_IN_SUB_QUEUE_FI" MODIFY ("PACK_ID" NOT NULL ENABLE);
  ALTER TABLE "XREF_IN_SUB_QUEUE_FI" MODIFY ("GROUP_PACK" NOT NULL ENABLE);