SELECT 
  BT.TARIFF_CODE,
  T.NAME                  TARIFF,
  BT.CLASS_CODE           CLASS,
  TC.NAME                 CLASS_NAME,
  BT.CATEGORY_CODE        CAT,
  TG.NAME                 CAT_NAME,
  TB.NAME                 PERIOD,
  BT.UNIT_DURATION,
  BT.UNIT_COST,
  T.BUNDLED               BUNDLS,
  T.BUNDLED_AMOUNT*1.2    "TF.BUNDLED_AMOUNT*1.2"

FROM  JAN.BANDUNIT_TARIFF BT, JAN.TARIFF T, JAN.TARIFF_CLASS TC, JAN.BAND TB, JAN.TARIFF_CATEGORY TG,
  JAN.SYSTEM_FIELD SF
WHERE  BT.TARIFF_CODE = '311'
AND  T.CODE=BT.TARIFF_CODE
AND  TC.CLASS_CODE=BT.CLASS_CODE
AND  TB.CODE=BT.BAND_CODE      
AND  TG.CODE=BT.CATEGORY_CODE
ORDER BY BT.CLASS_CODE, BT.CATEGORY_CODE, BT.BAND_CODE
